### PR TITLE
Map Pop Up

### PR DESCRIPTION
**Pull request by mwernimont**
Added the pop to the map. 

It disappears when you either click the X or off the pop up, it will not disappear when you click directly on the pop up.

Mobile it gets much smaller and you scroll inside the div to read the the whole thing. I thought this was the best solution since scrolling the page with a map could become problematic. The disappearing rules apply the same on mobile too.

@mhines-usgs wanna to check the code and test? @jread-usgs Yous probably wanna test too

### CODE REVIEW

**Comment by mhines-usgs** [comment]
Looks alright, might want to consider shortening the text if you REALLY expect someone to read it..
Also, the X on mobile does get very cozy with the title PLEASE READ FIRST, why not put a button at the bottom of the message after considering how much text you really expect folks to read? Just my 2 copper abes...

image

image

**Comment by mwernimont** [comment]
I mentioned the text length, @jread-usgs Is hoping to cut it down, which would help with design. And good point on the mobile X. Thank you @mhines-usgs

**Comment by mhines-usgs** [comment]
Yup, no problemo. Good luck! Great job getting it wedged in there, though!!

**Comment by jordansread** [comment]
@gjahansen2 thoughts on this?

**Comment by mwernimont** [comment]
Added a little more space between the title and the escape x on mobile, which looks a ton better

**Comment by gjahansen2** [comment]
I am torn about the length of the text. I agree that it is pretty long, so the downside of that is that they won't read it. However, I feel like we need to cover our butts a little bit so when people get all freaked out that 'their' lake is not predicted to have walleye, they understand what that means. In some ways, I feel better knowing the information is there, even if they don't read it, so we can point to it and say "don't freak out. Read this.".

That said, I can work on shortening the text.

One idea - I could imagine people skipping over it, going to the map, and then having some questions and wanting to go back and read it. Once it disappears, is there a way to get it back? Like have a "read instructions/disclaimer" button on the main map?

**Comment by gjahansen2** [comment]
Also, it looks great! Thanks you guys!

**Comment by mhines-usgs** [comment]
Yeah, maybe @mwernimont can figure out a show/hide div and include a link in the legend or layer selector "about this map" or something? (let me know if I can help work that in mtown!)

**Comment by mwernimont** [comment]
Thats pretty possible, will get on it

**Comment by mhines-usgs** [comment]
One other thing, I don't think you have to double-click to get the pop up on the lakes, but maybe it behaves differently depending on the browser.

**Comment by mwernimont** [comment]
Added a button to have the pop up to reappear for non readers wanting to read after all.

**Comment by gjahansen2** [comment]
You are right, we could change to just "click".

**Comment by mwernimont** [comment]
Want that changed then?

**Comment by gjahansen2** [comment]
@mwernimont yes please.

**Comment by mwernimont** [comment]
Now says Click instead of double clicking

**Pull request merged**
