### PR TITLE
initial content commit

### PR DESCRIPTION
**Pull request by jordansread**

### CODE REVIEW

**Comment by jordansread** [comment]
@jiwalker-usgs @aappling-usgs can you look at https://github.com/USGS-VIZLAB/climate-fish-habitat/pull/12/commits/eaa69293731a008043328806eeff89ead0598733

@lawinslow the rest is some prototype code that i will start working into the proper download->munge->vis pipeline

**Comment by lawinslow** [comment]
Can I merge this so we can be on the same page?

**Comment by lawinslow** [comment]
or are you still editing?

**Comment by jordansread** [comment]
go for it

I am going to work on background images now

**Comment by aappling-usgs** [comment]
@jread-usgs - jordan w and i just finished hashing out the structure of the latter sections. those will need to be changed a bit, but what you have looks like a good holding place until i can get the makefile maker made. so here's a belated :+1: to the above.

**Pull request merged**
