### PR TITLE
minor mods to text and layout, adding other lib scripts

### PR DESCRIPTION
**Pull request by jordansread**

### CODE REVIEW

**Comment by jordansread** [comment]
added some helpers per @lindsaycarr review:
image

**Comment by jordansread** [comment]
to get the fig in there:

```
cp sandbox/fishGDDFig-desktop.svg target/fishGDDFig-desktop.svg 
```

from terminal

**Comment by jordansread** [comment]
@lindsaycarr 
- [x] `before being told it was a "draw your own" scenario, I thought it was broken. There will obviously be more context around this in the actual viz, but I also think that the figure should be able to stand alone.`
  I added context, but kept it out of the figure because I didn't want it to get too busy. PR edits to those helpers if you have suggestions
- [x] `I don't think it is clear that the yellow appears in the sections that are incomplete. The New York Time one blinks - but maybe text can say "keep drawing" instead of it blinking (thinking of things being stand alone again)`
  I skipped this for now but made the yellow bars stand out more. I wasn't sure of a way where I could do what you are asking for gracefully (and w/o a bunch of work to make sure the text appears in a helpful location). 
- [x] `you can click at any height of the graph and it starts drawing Walleye. I would say that there needs to be a larger buffer around LMB hint segments because you currently have to click directly on the first point`
  This should be fixed for the first click, but I didn't change it for your later clicks. So, you "select" the fish you want to draw with your first click, as it takes the closest point to your click (wally or bass) and assigns that. Let me know what you think. 
- [ ] `I can change those hint segments by dragging my mouse over them. I think they should be fixed
  I like that you can change points after drawing them already`
  I did this on purpose so that the user would have full control over the whole pattern. Curious what others think @gjahansen2 
- [ ] `Incorporate a "Draw again" button so that people can completely start over (even after revealing the true lines)? Just thinking that people might want to show others the cool fig during the same session`
  I skipped this for now as I didn't want too many paths to be possible when interacting with the fig. That tends to make it more complicated to make sure everthing resets properly. Can add in the future if it is a priority. 
- [ ] `I know we are probably trying to not do exactly what the NYT fig did, but I really liked how they overlaid your guess with the real line. I might have drawn a couple of the points exactly, but it's hard to tell when you're looking on two different plots`
  The "finished" view is really a placeholder. I want to do an overlay, but haven't come up with a good way to do it that isn't too busy.

**Comment by lindsayplatt** [comment]
@jread-usgs reviewed it based on the suggestions I made - only thing that is not addressed is whether the user should be able to change the hints. Figured we could merge and change that later if needed

**Comment by jordansread** [comment]
:shipit:

**Comment by gjahansen2** [comment]
I think the hint section has too many words. Do we need all that? I would skip all or most of it.

I agree the true relationship  should be overlain with what you drew.

Is there some text that will come along with the true relationship?

I think it is ok that you can change the hint segments.

**Comment by jordansread** [comment]
yep, the "real relationship" experience is a placeholder now and if you want to think about it and suggest what should happen, I am all ears. Probably comment on #25

**Comment by jordansread** [comment]
@gjahansen2 did you have thoughts on this? ☝️ 

```
I can change those hint segments by dragging my mouse over them. I think they should be fixed
```

from jordan:  I did this on purpose so that the user would have full control over the whole pattern. Curious what others think @gjahansen2

**Comment by gjahansen2** [comment]
see above - I like that you can change the hint segments

**Comment by jordansread** [comment]
whoops, see it now

**Pull request merged**
